### ISSUE TITLE
Update Each Module with Suggested Content

### ISSUE THREAD

**Issue by bryceglass** [Esaron/trash-panda#13]
In each card, I've added a kid-friendly text blurb. Please add those, and make the fonts BIG AND FRIENDLY.

- [x] Animal Behavior #8
- [x] Animal Anatomy and Biology #7 
- [x] Scientific Name and Classification #6 
- [x] Animal Habitat Information #5 
- [x] Mating and Reproduction Information #4 
- [x] Diet information #3 
- [x] Home Page #1
