### ISSUE TITLE
Overall Site Navigation

### ISSUE THREAD

**Issue by bryceglass** [Esaron/trash-panda#9]
**According to the requirements**, here are the pages that should be generally accessible from the site Nav. Use this issue just to confirm, and as a checklist: 

- [x] Animal Behavior
- [x] Animal Anatomy and Biology #7 
- [x] Scientific Name and Classification #6 
- [x] Animal Habitat Information #5 
- [x] Mating and Reproduction Information #4 
- [x] Diet information #3 
- [x] Image Gallery #2 
- [x] Home Page #1
